### ISSUE TITLE
More discussions 

### ISSUE THREAD

**Issue by WeiFoo** [ai-se/tunelearners#28]
RQ1, 2 and 3 are fine I think.
We probably need a little more discussions about RQ4 and RQ5, actually, the same thing:
WHY tuning is so easy and fast!

**Comment by timm** [comment]
i will do

**Comment by timm** [comment]
ok. more text. thinking...

RQ1: what could be the extended text? (section 4.1)
- last time, there was a complain that tuned CART did not do much better than RF.
- comment to add: our case is not that we do vastly better but just that prior pessimism on CART being mostly inferior (from LESSMANN ) did not take into account tuning. We note here that, after tuning, the performance of these systems becomes comparable.

i think RQ2 is covered(section 4.2)
- we extended the discussion on Lessmann and added notes and results from Hall et al

um, RQ3? (section 4.3)
- the puzzle here is that difference systems offer different factors. that is the usual result from data mining but it is the weirdest thing to explain to outsiders. does the following sound even remotely convincing
- the variance in what variables are selected is quite large. elsewhere there are some preliminary results suggesting that these features are really surface aberrations of some underlying structure (perhaps modeled by the eigenvectors of the data). We conjecture that tuning exposes different parts of that underlying structure, hence different surface features appear in Table due to different tunings. 

um RQ4:  (section 4.4)
- we added more stats. is there some conceptual issue we could also explore?

rQ5: (section 4.5)
- the thing here is the core puzzle of this paper, why are we so fast? why has not this been seen before?  perhaps everyone else has elected to make complex explorations of this issue (e.g. GAs tuning parameters of a SVM kernel). here, we tried a different approach inspired by methodological statements of leaders in experimental methods in our field. before working on the more complex, collect baselines from some simpler alternatives (in this case, a DE with np=10). In this case of this work, the surprising result was that the simpler baseline method performed so remarkably well. Clearly, other methods than DE(np=10) might no better  that the results shown here. That said, for pragmatic reasons, it is useful to offer industrial practitioners a relatively simple to understand   (and simple to build-- see sample implementations at Stron's page).  also, from a  research perspective our results could serve as a baseline from which future work

**Comment by WeiFoo** [comment]
RQ1: also one reviewer complains WHY score of F is not as good as precision. F = pd*prec/(pd+prec), we can't get hight pd along with prec. probably because of the nature of learners, or the data sets used.

RQ5: we have to add those explanations about why tuning is so fast. I like your reasonings. 

For other RQ's, I think we are fine

**Comment by timm** [comment]
> For other RQ's, I think we are fine

@WeiFoo : sorry-- do you mean my other text for the RQs are fine or that we don't really need my text cause the other RQs are fine as it is? i'm good either way.. just want your clarification

**Comment by WeiFoo** [comment]
For QR2, 3, 4, I think we've already added some discussions there,  before I find any issue to explain, they're fine as it is.

**Comment by timm** [comment]
got it... just RQ1 and RQ5. will do

**Comment by WeiFoo** [comment]
@timm  I propose to argue that tuning can't guarantee to improve performance for any data sets. here're my arguments. please advise

Tuning can improve the performance of the target goals, which is based on the average observation from 17 datasets used in our experiments. However,  in some data sets, tuning may not improve but degrade the performance. For example,  Where gets worse score in precision over 3 datasets. As to why tuning fails in some data sets, one possible reason is that those data sets have a skew distribution and tuner can't find better peaks within limited tries. How to select data instances to make an appropriate searching space is an open question worthy further investigation.

**Comment by timm** [comment]
not too keen on the above. that is a Loooong disucssion which no one ever answered
